export type AdminModule = {
  key: string;
  title: string;
  href: string;
  description: string;
  collection?: string;
  status: "ready" | "base";
  required: boolean;
  group: "settings" | "operations" | "reports" | "resources" | "content";
};

export const adminModules: AdminModule[] = [
  {
    key: "blog",
    title: "Blog institucional",
    href: "/admin/blog",
    description: "Edicion de publicaciones, portadas y contenido institucional.",
    collection: "blog_posts",
    status: "ready",
    required: true,
    group: "content",
  },
  {
    key: "audits",
    title: "Auditorias",
    href: "/admin/auditorias",
    description: "Registro de cambios realizados por usuarios del sistema.",
    collection: "audit_logs",
    status: "ready",
    required: true,
    group: "content",
  },
  {
    key: "gallery",
    title: "Galeria",
    href: "/admin/galeria",
    description: "Imagenes de servicios por categoria para la pagina institucional.",
    collection: "gallery_images",
    status: "ready",
    required: true,
    group: "content",
  },
  {
    key: "certifications",
    title: "Certificaciones",
    href: "/admin/certificaciones",
    description: "Documentos e imagenes de respaldo institucional.",
    collection: "certifications",
    status: "ready",
    required: true,
    group: "content",
  },
  {
    key: "backups",
    title: "Respaldos",
    href: "/admin/respaldos",
    description: "Exportacion de respaldo de la informacion del sistema.",
    status: "ready",
    required: true,
    group: "content",
  },
  {
    key: "roles",
    title: "Login y roles",
    href: "/admin/roles",
    description: "Autenticacion, roles, permisos y accesos por modulo.",
    collection: "users",
    status: "ready",
    required: true,
    group: "settings",
  },
  {
    key: "users",
    title: "Usuarios",
    href: "/admin/usuarios",
    description: "Creacion y administracion de usuarios internos.",
    collection: "users",
    status: "ready",
    required: true,
    group: "settings",
  },
  {
    key: "workers",
    title: "Trabajadores",
    href: "/admin/trabajadores",
    description: "Personal, hojas de vida, cargos, novedades y documentos.",
    collection: "workers",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "dashboard-supervisor",
    title: "Dashboard supervisor",
    href: "/admin/dashboard-supervisor",
    description: "Reportes enviados, pendientes, observados y aprobados por supervisor.",
    collection: "supervisor_reports",
    status: "ready",
    required: true,
    group: "reports",
  },
  {
    key: "dashboard-accounting",
    title: "Dashboard contabilidad",
    href: "/admin/dashboard-contabilidad",
    description: "Valores pendientes, aprobados y generados para roles de pago.",
    collection: "supervisor_reports",
    status: "ready",
    required: true,
    group: "reports",
  },
  {
    key: "worker-intake",
    title: "Formulario nuevos trabajadores",
    href: "/admin/nuevos-trabajadores",
    description: "Ingreso inicial de trabajadores y carga de hoja de vida.",
    collection: "worker_intakes",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "worker-documents",
    title: "Control documental",
    href: "/admin/documentos-trabajadores",
    description: "Cedulas, certificados, contratos y documentos laborales.",
    collection: "worker_documents",
    status: "ready",
    required: true,
    group: "resources",
  },
  {
    key: "labor-history",
    title: "Historial laboral",
    href: "/admin/historial-laboral",
    description: "Expediente historico de asistencia, permisos, faltas y multas.",
    collection: "supervisor_reports",
    status: "ready",
    required: true,
    group: "reports",
  },
  {
    key: "work-groups",
    title: "Grupos de trabajo",
    href: "/admin/grupos-trabajo",
    description: "Catalogo de grupos, supervisores responsables y asignacion de personal.",
    collection: "work_groups",
    status: "ready",
    required: true,
    group: "settings",
  },
  {
    key: "catalogs",
    title: "Catalogos",
    href: "/admin/catalogos",
    description: "Catalogos generales reutilizables del sistema.",
    collection: "employee_positions",
    status: "ready",
    required: true,
    group: "settings",
  },
  {
    key: "service-types",
    title: "Tipos de servicios",
    href: "/admin/tipos-servicios",
    description: "Tipos de servicios ofrecidos y usados en contratos.",
    collection: "service_types",
    status: "ready",
    required: true,
    group: "settings",
  },
  {
    key: "clients",
    title: "Clientes",
    href: "/admin/clientes",
    description: "Clientes, sedes, contactos, contratos y requerimientos.",
    collection: "clients",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "contracts-shifts",
    title: "Contratos / areas / turnos",
    href: "/admin/contratos-turnos",
    description: "Contratos, areas asignadas, turnos y programacion operativa.",
    collection: "contracts",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "supervisor-daily-report",
    title: "Reporte diario del supervisor",
    href: "/admin/reporte-supervisor",
    description: "Reporte de asistencia, novedades, horas, reemplazos y soportes.",
    collection: "supervisor_reports",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "report-approvals",
    title: "Aprobacion de reportes",
    href: "/admin/aprobacion-reportes",
    description: "Revision, aprobacion y observaciones de reportes operativos.",
    collection: "report_approvals",
    status: "base",
    required: true,
    group: "reports",
  },
  {
    key: "accounting",
    title: "Contabilidad",
    href: "/admin/contabilidad",
    description: "Pagos, soportes, descuentos, multas y movimientos contables.",
    collection: "accounting_entries",
    status: "base",
    required: true,
    group: "operations",
  },
  {
    key: "payment-calculation",
    title: "Calculo de pagos",
    href: "/admin/calculo-pagos",
    description: "Horas trabajadas, horas extras, recargos y liquidacion.",
    collection: "payroll_periods",
    status: "base",
    required: true,
    group: "operations",
  },
  {
    key: "exports",
    title: "Reportes PDF / Excel",
    href: "/admin/reportes",
    description: "Informes descargables para administracion, RRHH y contabilidad.",
    collection: "exports",
    status: "base",
    required: true,
    group: "reports",
  },
  {
    key: "machines",
    title: "Equipos de limpieza",
    href: "/admin/equipos",
    description: "Inventario de equipos para hospitales, instituciones, hogares y talleres.",
    collection: "machines",
    status: "ready",
    required: true,
    group: "resources",
  },
  {
    key: "supply-products",
    title: "Productos / insumos",
    href: "/admin/productos-insumos",
    description: "Catalogo de productos disponibles para armar kits mensuales.",
    collection: "supply_products",
    status: "ready",
    required: true,
    group: "resources",
  },
  {
    key: "supply-kits",
    title: "Kit de insumos mensual",
    href: "/admin/kits-insumos",
    description: "Lista mensual de insumos por contrato y lugar de trabajo.",
    collection: "supply_kits",
    status: "ready",
    required: true,
    group: "resources",
  },
  {
    key: "supply-control",
    title: "Control de insumos",
    href: "/admin/control-insumos",
    description: "Entrega, consumo y pendientes de insumos por cliente.",
    collection: "supply_movements",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "hiring-processes",
    title: "Procesos de contratacion",
    href: "/admin/procesos-contratacion",
    description: "Procesos por numero, cronograma y estado actualizado.",
    collection: "hiring_processes",
    status: "ready",
    required: true,
    group: "operations",
  },
  {
    key: "process-calendar",
    title: "Calendario de procesos",
    href: "/admin/calendario-procesos",
    description: "Fechas importantes, alertas y vencimientos de procesos.",
    collection: "hiring_processes",
    status: "ready",
    required: true,
    group: "reports",
  },
  {
    key: "process-tracking",
    title: "Seguimiento de procesos",
    href: "/admin/seguimiento-procesos",
    description: "Metricas de avance por proceso y empresa participante.",
    collection: "hiring_processes",
    status: "ready",
    required: true,
    group: "reports",
  },
  {
    key: "notifications",
    title: "Notificaciones",
    href: "/admin/notificaciones",
    description: "Alertas internas por rol para reportes, documentos y procesos.",
    collection: "notifications",
    status: "ready",
    required: true,
    group: "reports",
  },
];

export const settingsModules = adminModules.filter((module) => module.group === "settings");
export const operationsModules = adminModules.filter((module) => module.group === "operations");
export const resourcesModules = adminModules.filter((module) => module.group === "resources");
export const reportsModules = adminModules.filter((module) => module.group === "reports");
export const contentModules = adminModules.filter((module) => module.group === "content");

export function getModuleByKey(key: string) {
  return adminModules.find((module) => module.key === key);
}
